/**
 * Harvest — cold-start memory from the transcripts your agents already wrote.
 *
 * A fresh brain is empty, and an empty brain is worth nothing until someone
 * feeds it. But every coding agent already keeps a local record of months of
 * work: prompts, decisions, corrections, preferences. This module reads those
 * records and turns them into a *digest* — a deterministic, budget-bounded
 * summary of candidate sessions.
 *
 * What this module deliberately does NOT do is decide what is worth
 * remembering. That is a semantic judgement, and Brain's whole design puts
 * semantic judgement in the agent (see CLAUDE.md, "Agent-driven intelligence").
 * Doing extraction here would mean shipping an embedding model or calling an
 * LLM — the two things Brain exists to avoid. So the split is:
 *
 *   harvest (this file, deterministic)  →  digest
 *   digest  →  agent reads it           →  `brain memorize` (existing path)
 *
 * The agent's distillation is `agent-inferred` provenance by construction, so
 * imported memories inherit the existing ASI06 ceilings for free: an import can
 * never pin, never entrench, and never outrank something the user said directly.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');

const { getBrainDir, atomicWriteSync } = require('./index-manager');

// --- Budgets ---
//
// A 500-session history would blow any context window, so the digest is capped
// on three independent axes. Sessions are the coarse cap, prompts the medium,
// and total characters the backstop that holds even if a single session is
// pathological.
const DEFAULTS = {
  maxSessions: 40,
  maxPromptsPerSession: 6,
  maxPromptChars: 400,
  maxDigestChars: 60000, // ~15k tokens at chars/4
};

// Sessions below this many real user prompts are almost always a mis-start, a
// one-line question, or an aborted run. They cost digest budget and yield
// nothing memorable.
const MIN_PROMPTS = 2;

// --- Text cleaning ---

// Harness-injected wrappers that are not user speech. Left in, they dominate the
// digest and teach the agent to memorize plumbing.
const STRIP_PATTERNS = [
  /<system-reminder>[\s\S]*?<\/system-reminder>/g,
  /<command-name>[\s\S]*?<\/command-name>/g,
  /<command-message>[\s\S]*?<\/command-message>/g,
  /<command-args>[\s\S]*?<\/command-args>/g,
  /<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g,
  /<local-command-stderr>[\s\S]*?<\/local-command-stderr>/g,
  /<user-prompt-submit-hook>[\s\S]*?<\/user-prompt-submit-hook>/g,
  // Brain's own hook injections (hooks/*.mjs) — recalled memories must never be
  // harvested back into new memories.
  /<brain-session-context>[\s\S]*?<\/brain-session-context>/g,
  /<brain-context>[\s\S]*?<\/brain-context>/g,
  /\[Image #\d+\]/g,
  /\[Request interrupted[^\]]*\]/g,
];

// Whole prompts that carry no intent worth remembering.
const NOISE_PROMPTS = [
  /^caveat: the messages below were generated by the user while running local commands/i,
  /^\/[a-z0-9:_-]+\s*$/i, // a bare slash-command invocation
  /^(y|n|yes|no|ok|okay|k|sure|thanks|thank you|ty|continue|go|go ahead|proceed|yep|yeah|nope)\b[.!]*$/i,
];

/** Strip harness wrappers and normalize whitespace. Returns '' for pure noise. */
function cleanPromptText(raw) {
  if (typeof raw !== 'string') return '';
  let text = raw;
  for (const pattern of STRIP_PATTERNS) text = text.replace(pattern, ' ');
  text = text.replace(/\s+/g, ' ').trim();
  if (!text) return '';
  if (NOISE_PROMPTS.some((p) => p.test(text))) return '';
  return text;
}

/** Truncate on a word boundary so the digest never ends mid-token. */
function truncate(text, max) {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return (lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd() + '…';
}

/**
 * Pull the user-authored text out of one transcript record.
 *
 * `message.content` is either a bare string (older transcripts) or an array of
 * blocks. Only `text` blocks are user speech — `tool_result` blocks are replayed
 * command output that merely happens to be recorded under the user role.
 */
function userTextFrom(record) {
  const content = record && record.message && record.message.content;
  if (typeof content === 'string') return cleanPromptText(content);
  if (!Array.isArray(content)) return '';
  return cleanPromptText(
    content
      .filter((block) => block && block.type === 'text' && typeof block.text === 'string')
      .map((block) => block.text)
      .join('\n')
  );
}

// --- JSONL reading ---

/**
 * Parse a JSONL transcript, skipping unparseable lines.
 *
 * Transcripts are appended to live by a running agent, so the final line of an
 * in-flight session is routinely a partial write. That is expected, not an
 * error: skip the line and keep the rest of the session.
 */
function readJsonl(file) {
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf-8');
  } catch (_) {
    return [];
  }
  const records = [];
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    try {
      records.push(JSON.parse(line));
    } catch (_) {
      // Truncated tail or corrupt line — skip.
    }
  }
  return records;
}

// --- Source adapters ---
//
// Each adapter turns one agent's on-disk history into a common session shape.
// Adding a source means adding an entry here; nothing downstream changes.

const FILE_EDIT_TOOLS = new Set(['Edit', 'Write', 'NotebookEdit', 'MultiEdit']);

/**
 * Claude Code — one JSONL file per session under ~/.claude/projects/<slug>/.
 *
 * The directory slug is a lossy encoding of the working directory (every path
 * separator and literal dash both become '-'), so it cannot be decoded back
 * reliably. Records carry the real `cwd`, so we read it from there and keep the
 * slug only as a last resort.
 */
const claudeCode = {
  id: 'claude-code',
  label: 'Claude Code',
  root: () => path.join(os.homedir(), '.claude', 'projects'),

  listFiles(root) {
    let dirs;
    try {
      dirs = fs.readdirSync(root, { withFileTypes: true });
    } catch (_) {
      return [];
    }
    const files = [];
    for (const dir of dirs) {
      if (!dir.isDirectory()) continue;
      const dirPath = path.join(root, dir.name);
      let entries;
      try {
        entries = fs.readdirSync(dirPath);
      } catch (_) {
        continue;
      }
      // Deliberately one level deep. Nested `<session-id>/subagents/*.jsonl`
      // files are subagent transcripts — delegated tool traffic containing no
      // user speech, and on this machine they outnumber real sessions almost
      // 1:1. Recursing would double the scan cost to harvest pure noise.
      for (const name of entries) {
        if (name.endsWith('.jsonl')) files.push(path.join(dirPath, name));
      }
    }
    return files.sort();
  },

  parse(file) {
    const records = readJsonl(file);
    if (records.length === 0) return null;

    const session = {
      source: 'claude-code',
      session_id: null,
      title: null,
      cwd: null,
      git_branch: null,
      started: null,
      ended: null,
      models: new Set(),
      prompts: [],
      files_touched: new Set(),
      turns: 0,
    };

    for (const record of records) {
      if (!record || typeof record !== 'object') continue;
      if (record.sessionId && !session.session_id) session.session_id = record.sessionId;

      // Claude Code names sessions itself. That title is a free, already-curated
      // summary — far better than anything we could derive with regexes.
      if (record.type === 'ai-title' && record.aiTitle) session.title = record.aiTitle;

      if (record.cwd) session.cwd = record.cwd;
      if (record.gitBranch) session.git_branch = record.gitBranch;
      if (record.timestamp) {
        if (!session.started || record.timestamp < session.started) session.started = record.timestamp;
        if (!session.ended || record.timestamp > session.ended) session.ended = record.timestamp;
      }

      // Sidechain records are subagent traffic, not the user talking.
      if (record.isSidechain || record.isMeta) continue;

      if (record.type === 'user') {
        const text = userTextFrom(record);
        if (text) session.prompts.push(text);
      }

      if (record.type === 'assistant') {
        session.turns++;
        const model = record.message && record.message.model;
        if (model) session.models.add(model);
        const content = (record.message && record.message.content) || [];
        if (Array.isArray(content)) {
          for (const block of content) {
            if (block && block.type === 'tool_use' && FILE_EDIT_TOOLS.has(block.name)) {
              const target = block.input && (block.input.file_path || block.input.notebook_path);
              if (target) session.files_touched.add(target);
            }
          }
        }
      }
    }

    if (!session.session_id) session.session_id = path.basename(file, '.jsonl');
    if (!session.cwd) session.cwd = slugToPathGuess(path.basename(path.dirname(file)));
    return session;
  },
};

/**
 * Best-effort recovery of a working directory from a Claude Code project slug.
 *
 * Lossy by nature — '-Users-me-code-my-app' could be '/Users/me/code/my-app' or
 * '/Users/me/code/my/app'. Only used when no record carried a real `cwd`, and
 * only to label the session, never to write anything.
 */
function slugToPathGuess(slug) {
  if (!slug || !slug.startsWith('-')) return slug || null;
  return '/' + slug.slice(1).replace(/-/g, '/');
}

/**
 * OpenAI Codex CLI — one JSONL "rollout" per thread under
 * `$CODEX_HOME/sessions/YYYY/MM/DD/rollout-<ts>-<thread>[_<rollout>].jsonl`
 * (verified against openai/codex 0.153, codex-rs/rollout/). Every line is
 * `{timestamp, ordinal?, type, payload}`; the user's prompts are
 * `response_item` messages with `role: "user"`.
 *
 * Codex also injects context *as user-role messages* (AGENTS.md, the
 * environment block, turn-aborted notices, hook output). Since 0.148 genuine
 * prompts carry `internal_chat_message_metadata_passthrough.content_item_kinds`
 * containing `user.*`, which is the reliable discriminator; older rollouts lack
 * it, so the wrapper markers Codex renders are the fallback.
 */
const CODEX_INJECTED_MARKERS = [
  /^\s*# AGENTS\.md instructions/i,
  /^\s*<user_instructions>/i,
  /^\s*<environment_context>/i,
  /^\s*<turn_aborted>/i,
  /^\s*<user_shell_command>/i,
  /^\s*<subagent_notification>/i,
  /^\s*<codex_internal_context/i,
  /^\s*<goal_context>/i,
  /^\s*<hook_prompt/i,
  /^\s*<brain-/i,
];

// rollout-YYYY-MM-DDTHH-MM-SS-<thread>[_<rollout>].jsonl → the id token
const CODEX_ROLLOUT_NAME = /^rollout-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-(.+)\.jsonl$/;

// Threads Codex runs for itself (subagents, guardian reviews, memory
// consolidation) contain no user speech.
const CODEX_BACKGROUND_THREADS = new Set(['subagent', 'guardian_review', 'memory_consolidation']);

function codexHome() {
  return process.env.CODEX_HOME || path.join(os.homedir(), '.codex');
}

function codexInputText(payload) {
  const content = Array.isArray(payload.content) ? payload.content : [];
  return content
    .filter((block) => block && block.type === 'input_text' && typeof block.text === 'string')
    .map((block) => block.text)
    .join('\n');
}

function codexIsUserAuthored(payload) {
  const meta = payload.internal_chat_message_metadata_passthrough;
  const kinds = meta && Array.isArray(meta.content_item_kinds) ? meta.content_item_kinds : [];
  if (kinds.length > 0) {
    return kinds.some((k) => typeof k === 'string' && (k.startsWith('user.') || k === 'unknown'));
  }
  return !CODEX_INJECTED_MARKERS.some((marker) => marker.test(codexInputText(payload)));
}

function codexIsBackgroundThread(meta) {
  if (meta.parent_thread_id) return true;
  if (typeof meta.thread_source === 'string' && CODEX_BACKGROUND_THREADS.has(meta.thread_source)) return true;
  const source = meta.source;
  return Boolean(source && typeof source === 'object' && ('subagent' in source || 'internal' in source));
}

/**
 * User-assigned thread names from `$CODEX_HOME/session_index.jsonl` (last
 * entry per id wins). Cached per home dir — one read per harvest.
 */
const codexThreadNames = new Map();
function codexThreadName(home, threadId) {
  if (!codexThreadNames.has(home)) {
    const names = new Map();
    for (const entry of readJsonl(path.join(home, 'session_index.jsonl'))) {
      if (entry && typeof entry.id === 'string' && typeof entry.thread_name === 'string') {
        names.set(entry.id, entry.thread_name);
      }
    }
    codexThreadNames.set(home, names);
  }
  return codexThreadNames.get(home).get(threadId) || null;
}

const codex = {
  id: 'codex',
  label: 'OpenAI Codex CLI',
  root: () => path.join(codexHome(), 'sessions'),

  listFiles(root) {
    // Exactly sessions/<year>/<month>/<day>/rollout-*.jsonl. Compressed
    // rollouts (`.jsonl.zst`, an opt-in Codex feature) are skipped.
    const files = [];
    const walk = (dir, depth) => {
      let entries;
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch (_) {
        return;
      }
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory() && depth < 3 && /^\d+$/.test(entry.name)) walk(full, depth + 1);
        else if (entry.isFile() && depth === 3 && CODEX_ROLLOUT_NAME.test(entry.name)) files.push(full);
      }
    };
    walk(root, 0);
    return files.sort();
  },

  /** Session id = the id token in the filename (unique per rollout file). */
  sessionIdFor(file) {
    const match = path.basename(file).match(CODEX_ROLLOUT_NAME);
    return match ? match[1] : path.basename(file, '.jsonl');
  },

  parse(file) {
    const records = readJsonl(file);
    if (records.length === 0) return null;

    const sessionId = codex.sessionIdFor(file);
    const session = {
      source: 'codex',
      session_id: sessionId,
      title: null,
      cwd: null,
      git_branch: null,
      started: null,
      ended: null,
      models: new Set(),
      prompts: [],
      files_touched: new Set(),
      turns: 0,
    };

    for (const record of records) {
      if (!record || typeof record !== 'object') continue;
      const payload = record.payload && typeof record.payload === 'object' ? record.payload : {};
      if (record.timestamp) {
        if (!session.started || record.timestamp < session.started) session.started = record.timestamp;
        if (!session.ended || record.timestamp > session.ended) session.ended = record.timestamp;
      }

      if (record.type === 'session_meta') {
        if (codexIsBackgroundThread(payload)) return null;
        if (payload.cwd) session.cwd = payload.cwd;
        if (payload.git && payload.git.branch) session.git_branch = payload.git.branch;
      } else if (record.type === 'turn_context') {
        if (payload.model) session.models.add(payload.model);
        if (payload.cwd && !session.cwd) session.cwd = payload.cwd;
      } else if (record.type === 'response_item') {
        if (payload.type === 'message' && payload.role === 'user') {
          if (!codexIsUserAuthored(payload)) continue;
          const text = cleanPromptText(codexInputText(payload));
          if (text) session.prompts.push(text);
        } else if (payload.type === 'message' && payload.role === 'assistant') {
          session.turns++;
        } else if (payload.type === 'custom_tool_call' && payload.name === 'apply_patch' && typeof payload.input === 'string') {
          for (const match of payload.input.matchAll(/^\*\*\* (?:Add|Update|Delete) File: (.+)$/gm)) {
            session.files_touched.add(match[1].trim());
          }
        }
      }
    }

    // <home>/sessions/YYYY/MM/DD/<file> → <home>; names are keyed by thread id.
    const home = path.resolve(path.dirname(file), '..', '..', '..', '..');
    session.title = codexThreadName(home, sessionId.split('_')[0]);
    return session;
  },
};

const SOURCES = { [claudeCode.id]: claudeCode, [codex.id]: codex };

/** Sources that actually have a history store on this machine. */
function availableSources() {
  return Object.values(SOURCES)
    .map((adapter) => {
      const root = adapter.root();
      const present = fs.existsSync(root);
      return {
        id: adapter.id,
        label: adapter.label,
        root,
        available: present,
        sessions: present ? adapter.listFiles(root).length : 0,
      };
    });
}

// --- Import state ---
//
// Import is incremental. Without a cursor, a second run re-offers every session
// and the agent writes the same memories again — the fastest way to poison a
// brain with duplicates.

function importStatePath(projectRoot) {
  return path.join(getBrainDir(projectRoot), '.import', 'state.json');
}

function readImportState(projectRoot) {
  try {
    const parsed = JSON.parse(fs.readFileSync(importStatePath(projectRoot), 'utf-8'));
    if (parsed && typeof parsed === 'object' && parsed.sources) return parsed;
  } catch (_) {
    // Missing or corrupt — a fresh cursor is always safe, it only means the
    // next run re-offers sessions the agent can recognize as already-known.
  }
  return { version: 1, sources: {} };
}

function writeImportState(state, projectRoot) {
  const file = importStatePath(projectRoot);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  atomicWriteSync(file, JSON.stringify(state, null, 2) + '\n');
}

/**
 * Record sessions as imported so later runs skip them.
 *
 * Ids are checked against the source's real sessions first. A silently accepted
 * typo or truncated id is the worst possible failure here: the caller is told
 * the session is done, the cursor never matches it, and the session is re-offered
 * forever — so unknown ids are reported back rather than written.
 *
 * When the source's history is not enumerable — an unregistered source, or a
 * store that isn't on this machine — there is nothing to check against, so ids
 * are accepted as given rather than rejected on no evidence.
 *
 * @param {string} sourceId
 * @param {string[]} sessionIds
 * @param {string} [projectRoot] - Filesystem root whose .brain/ to use
 * @param {Set<string>} [knownIds] - Override the enumerated id set (tests)
 * @returns {{ added: number, total: number, unknown: string[] }}
 */
function markImported(sourceId, sessionIds, projectRoot, knownIds) {
  let known = knownIds || null;
  if (!known) {
    const adapter = SOURCES[sourceId];
    if (adapter) {
      const root = adapter.root();
      if (fs.existsSync(root)) {
        known = new Set(adapter.listFiles(root).map((f) =>
          (adapter.sessionIdFor ? adapter.sessionIdFor(f) : path.basename(f, '.jsonl'))));
      }
    }
  }

  const state = readImportState(projectRoot);
  if (!state.sources[sourceId]) state.sources[sourceId] = { imported: {} };
  const now = new Date().toISOString();

  const unknown = [];
  let added = 0;
  for (const id of sessionIds) {
    if (known && !known.has(id)) { unknown.push(id); continue; }
    if (!state.sources[sourceId].imported[id]) added++;
    state.sources[sourceId].imported[id] = now;
  }
  writeImportState(state, projectRoot);
  return {
    added,
    total: Object.keys(state.sources[sourceId].imported).length,
    unknown,
  };
}

// --- Digest ---

/** Deduplicate consecutive near-identical prompts (retries, resends). */
function dedupePrompts(prompts) {
  const out = [];
  const seen = new Set();
  for (const prompt of prompts) {
    const key = prompt.slice(0, 120).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(prompt);
  }
  return out;
}

/**
 * Pick which prompts represent the session.
 *
 * The opening prompt states the goal and the closing ones state what it became,
 * so both edges are kept and the middle is sampled. Taking the first N instead
 * would systematically lose every outcome.
 */
function selectPrompts(prompts, max) {
  if (prompts.length <= max) return prompts;
  const head = Math.ceil(max / 2);
  const tail = max - head;
  return [...prompts.slice(0, head), ...prompts.slice(prompts.length - tail)];
}

/**
 * Round-robin candidates across projects, preserving recency within each.
 *
 * Sorting by recency alone lets one busy repo eat the entire budget — on a real
 * 261-session history, one project took 32 of 38 slots and five others got a
 * single session between them. Cold-start value comes from breadth (the agent
 * learning that you work on N things, and what each one is) far more than from
 * depth in whichever repo you happened to touch last week.
 */
function interleaveByProject(candidates) {
  const byProject = new Map();
  for (const candidate of candidates) {
    const key = candidate.project || '(unknown)';
    if (!byProject.has(key)) byProject.set(key, []);
    byProject.get(key).push(candidate);
  }

  // Projects with recent activity lead, so the first round is the work most
  // likely to still be live.
  const queues = [...byProject.values()];
  const ordered = [];
  for (let round = 0; ordered.length < candidates.length; round++) {
    for (const queue of queues) {
      if (round < queue.length) ordered.push(queue[round]);
    }
  }
  return ordered;
}

/** Human-facing project label — the directory name is what users call a project. */
function projectNameOf(session) {
  if (!session.cwd) return null;
  return path.basename(session.cwd) || null;
}

/**
 * Build a budget-bounded digest of candidate sessions.
 *
 * @param {Object} [opts]
 * @param {string} [opts.source='claude-code'] - Source adapter id
 * @param {string} [opts.project] - Only sessions whose project name matches
 * @param {string} [opts.since] - ISO date; only sessions ended at/after it
 * @param {number} [opts.limit] - Max sessions in the digest
 * @param {boolean} [opts.all=false] - Include already-imported sessions
 * @param {string} [opts.projectRoot] - Filesystem root whose .brain/ to use
 * @returns {Object} digest payload
 */
function harvest(opts = {}) {
  const sourceId = opts.source || 'claude-code';
  const adapter = SOURCES[sourceId];
  if (!adapter) {
    return { error: `Unknown source "${sourceId}" (available: ${Object.keys(SOURCES).join(', ')})` };
  }

  const limit = opts.limit || DEFAULTS.maxSessions;
  const root = adapter.root();
  if (!fs.existsSync(root)) {
    return {
      source: sourceId,
      scanned: { files: 0, sessions: 0, skipped: 0, already_imported: 0 },
      sessions: [],
      note: `No ${adapter.label} history found at ${root}.`,
    };
  }

  const state = readImportState(opts.projectRoot);
  const done = (state.sources[sourceId] && state.sources[sourceId].imported) || {};

  const files = adapter.listFiles(root);
  const candidates = [];
  // Kept apart on purpose: `skipped` means "held nothing worth reading",
  // `filtered` means "excluded by your --project/--since scoping". Merging them
  // would report a scoped run as though it had discarded hundreds of bad
  // sessions, which is both alarming and false.
  let skipped = 0;
  let filtered = 0;
  let alreadyImported = 0;

  for (const file of files) {
    const session = adapter.parse(file);
    if (!session) { skipped++; continue; }

    if (!opts.all && done[session.session_id]) { alreadyImported++; continue; }

    const prompts = dedupePrompts(session.prompts);
    if (prompts.length < MIN_PROMPTS) { skipped++; continue; }

    const project = projectNameOf(session);
    if (opts.project && project !== opts.project) { filtered++; continue; }
    if (opts.since && session.ended && session.ended < opts.since) { filtered++; continue; }

    candidates.push({ session, prompts, project });
  }

  // Most recent first: recent work is both likelier to matter and likelier to
  // still be true. An import that runs out of budget should run out on the
  // oldest sessions, not the newest.
  candidates.sort((a, b) => String(b.session.ended || '').localeCompare(String(a.session.ended || '')));

  const ordered = interleaveByProject(candidates);

  const sessions = [];
  let chars = 0;
  let budgetTruncated = false;

  for (const candidate of ordered) {
    if (sessions.length >= limit) { budgetTruncated = true; break; }

    const { session, prompts, project } = candidate;
    const selected = selectPrompts(prompts, DEFAULTS.maxPromptsPerSession)
      .map((p) => truncate(p, DEFAULTS.maxPromptChars));

    const entry = {
      session_id: session.session_id,
      title: session.title || null,
      project,
      cwd: session.cwd,
      git_branch: session.git_branch || null,
      started: session.started,
      ended: session.ended,
      turns: session.turns,
      prompt_count: prompts.length,
      models: [...session.models],
      files_touched: [...session.files_touched]
        .map((f) => (session.cwd && f.startsWith(session.cwd) ? path.relative(session.cwd, f) : f))
        .slice(0, 12),
      prompts: selected,
    };

    const cost = JSON.stringify(entry).length;
    if (chars + cost > DEFAULTS.maxDigestChars && sessions.length > 0) {
      budgetTruncated = true;
      break;
    }
    chars += cost;
    sessions.push(entry);
  }

  return {
    source: sourceId,
    source_label: adapter.label,
    scanned: {
      files: files.length,
      candidates: candidates.length,
      returned: sessions.length,
      skipped,
      filtered,
      already_imported: alreadyImported,
      remaining: Math.max(0, candidates.length - sessions.length),
    },
    budget: {
      max_sessions: limit,
      max_digest_chars: DEFAULTS.maxDigestChars,
      used_chars: chars,
      token_estimate: Math.ceil(chars / 4),
      truncated: budgetTruncated,
    },
    sessions,
  };
}

module.exports = {
  harvest,
  availableSources,
  markImported,
  readImportState,
  writeImportState,
  importStatePath,
  // Exported for tests
  cleanPromptText,
  userTextFrom,
  selectPrompts,
  dedupePrompts,
  truncate,
  slugToPathGuess,
  readJsonl,
  SOURCES,
  DEFAULTS,
  MIN_PROMPTS,
};
